# Generated by Django 4.0.3 on 2022-10-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='color',
        ),
    ]
